### ISSUE TITLE
Mac OS Ventura support

### ISSUE THREAD

**Issue by Daess** [sindresorhus/osx-release#12]
Hi,

Mac OS Ventura is not listed in an array of supported OS, so builds starting to fail. It would be nice to get an update. 
The relevant problem was earlier mentioned in this issue: https://github.com/sindresorhus/macos-release/issues/8.

**Comment by Daess** [comment]
My bad, the issue was caused by library using this one as a dependency.

**Comment by smallstepstoday** [comment]
This is actually a current issue -- Ventura is not currently listed as a valid option, please re-open

**Comment by Daess** [comment]
@smallstepstoday it seems that the latest release contains the required fix: https://github.com/sindresorhus/macos-release/commit/9c6899c29f013e97200d027074a3cb0d55ac826b
