### ISSUE TITLE
support releases pre 10.5?

### ISSUE THREAD

**Issue by gabrielcsapo** [sindresorhus/osx-release#2]
Looks like 10.4 is also called `Tiger` https://en.wikipedia.org/wiki/Mac_OS_X_Tiger

**Comment by sindresorhus** [comment]
You're misunderstanding the numbering.

https://github.com/sindresorhus/macos-release/blob/0fd3f6c15ccf6ccc4727c0373c1bdd2d64d14c88/index.js#L14
